### ISSUE TITLE
Tips ✨

### ISSUE THREAD

**Issue by iambhvsh** [asadkhan7865571/asadwebsite#1]
When you add source or paths of some files make sure the path is always in lowercase letters, also don't create much Stylesheets and Javascript files instead create a one single file like for eg. `style.css`  and javascript file `script.js` and write all your code in those files by dividing them using comments like this:

---

``` css
body {
    // Some code here
}

navbar {
   // Some code here
}

// Other part which you want to divide after this comments like grids, layouts, etc

video-grid {
    // Some code here
}
```

Same goes with Javascript also!

---

Thank you,
[iambhvsh](https://iambhvsh.vercel.app) 🩷

**Comment by asadkhan7865571** [comment]
Noted Bhavesh! I was planning to do it soon. Thanks for highlighting it.
